// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.java.base.learn.grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_StudentRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\035com.java.base.learn.grp" +
      "c.demo1\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n" +
      "\nMyResponse\022\020\n\010realname\030\002 \001(\t\":\n\017Student" +
      "Response\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004c" +
      "ity\030\003 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005" +
      "2\367\001\n\016StudentService\022n\n\025GetRealNameByUser" +
      "name\022(.com.java.base.learn.grpc.demo1.MyR" +
      "equest\032).com.java.base.learn.grpc.demo1.M" +
      "yResponse\"\000\022u\n\020GetStudentsByAge\022-.com.ja" +
      "va.base.learn.grpc.demo1.StudentRequest\032." +
      ".com.java.base.learn.grpc.demo1.StudentRe" +
      "sponse\"\0000\001B/\n\035com.java.base.learn.grpc.d" +
      "emoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor,
        new String[] { "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
