// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.java.base.learn.grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\035com.java.base.learn.grp" +
      "c.demo\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n" +
      "\nMyResponse\022\020\n\010realname\030\001 \001(\t2\200\001\n\016Studen" +
      "tService\022n\n\025GetRealNameByUsername\022(.com." +
      "java.base.learn.grpc.demo.MyRequest\032).co" +
      "m.java.base.learn.grpc.demo.MyResponse\"\000" +
      "B/\n\035com.java.base.learn.grpc.demoB\014Stude" +
      "ntProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor,
        new String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
