// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.java.base.learn.grpc;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_java_base_learn_grpc_demo_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_java_base_learn_grpc_demo_StudentResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\035com.java.base.learn.grp" +
      "c.demo\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n" +
      "\nMyResponse\022\020\n\010realname\030\002 \001(\t\"\035\n\016Student" +
      "Request\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t" +
      "\"^\n\023StudentResponseList\022G\n\017studentRespon" +
      "se\030\001 \003(\0132..com.java.base.learn.grpc.demo" +
      ".StudentResponse2\373\002\n\016StudentService\022n\n\025G" +
      "etRealNameByUsername\022(.com.java.base.lea" +
      "rn.grpc.demo.MyRequest\032).com.java.base.l" +
      "earn.grpc.demo.MyResponse\"\000\022u\n\020GetStuden" +
      "tsByAge\022-.com.java.base.learn.grpc.demo." +
      "StudentRequest\032..com.java.base.learn.grp" +
      "c.demo.StudentResponse\"\0000\001\022\201\001\n\030GetStuden" +
      "tsWrapperByAges\022-.com.java.base.learn.gr" +
      "pc.demo.StudentRequest\0322.com.java.base.l" +
      "earn.grpc.demo.StudentResponseList\"\000(\001B*" +
      "\n\030com.java.base.learn.grpcB\014StudentProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_java_base_learn_grpc_demo_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_java_base_learn_grpc_demo_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_java_base_learn_grpc_demo_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_java_base_learn_grpc_demo_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_java_base_learn_grpc_demo_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_java_base_learn_grpc_demo_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_java_base_learn_grpc_demo_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
